### ISSUE TITLE
Default "Up to major version" dependency rule in Xcode incompatible with Pow's 0.X versioning

### ISSUE THREAD

**Issue by warpling** [EmergeTools/Pow#34]
Xcode's "up to major version" dependency by default is 1.0.0 < 2.0.0 which seems to conflict with Pow's 0.3.0 versioning.

<img width="1100" alt="image" src="https://github.com/movingparts-io/Pow/assets/220240/3dc81dc4-ae04-4bae-961f-bb8a24bac568">

**Comment by mergesort** [comment]
Hey @warpling, it seems like this problem is on Xcode’s side. [Semantically](https://semver.org/) there's nothing wrong with versioning a library in the 0.x.x range, the number is generally reserved for pre-release versions. I can understand from Xcode's side why they choose to assume that libraries are 1.0.0 and higher, but it still seems like they should handle pre-release libraries more gracefully.

The good news is that we just released version [1.0.0](https://github.com/EmergeTools/Pow/releases/tag/1.0.0), so this won't be a problem going forward regardless and I feel safe closing this issue out. 🙂
