### ISSUE TITLE
Feature Request: Support for Repeated Effect.

### ISSUE THREAD

**Issue by Addallah** [EmergeTools/Pow#57]
I couldn't get the animation to work with `.repeatForever()` .

I would love if there was a way to trigger the Effect every 2 seconds for example

**Comment by mergesort** [comment]
Hey @Addallah, would you be able to provide more context about your use case? Normally I would suggest updating the piece of state that triggers your animation on a timer that fires every two seconds rather than trying to repeat the animation forever, but I'd love to understand more about what you're trying to do to see if there's a worthwhile addition to the library that should be made.

Thanks a lot!

**Comment by Addallah** [comment]
I would like to take advantage of the shine animation for direct the user attention to a subscribe button for example.
![ShineEffectinAndroid](https://github.com/EmergeTools/Pow/assets/93667302/ff1e9cc8-c752-474f-8a09-ab53ebfdbcf0)

**Comment by Addallah** [comment]
The solution that i ended up with.

`.onAppear {
   _ = Timer.scheduledTimer(withTimeInterval: 5, repeats: true) { _ in
        withAnimation {
            shine.toggle()
        }
    }
}`


https://github.com/EmergeTools/Pow/assets/93667302/388dbb09-4cea-4417-8fa8-e2dad4f2b1b0

**Comment by mergesort** [comment]
Hey @Addallah, apologies that I hadn't responded I accidentally closed the tab and this issue went missing from Github Notifications. I love what you came up with, it looks great! And your solution looks great, it's pretty much exactly what I was suggesting above, well done. 😄
